channels:
  - conda-forge
  - mrtrix3
  - defaults
dependencies:
  - mrtrix3::mrtrix3
  - python=3.11
  - pip
  - pip:
    - numpy
    - scipy
    - pandas
    - matplotlib
    - ipython
    - nilearn
    - mne
